# Generated by Django 5.0.6 on 2024-07-01 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BooksApp.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BooksApp.book')),
            ],
        ),
    ]
