# Generated by Django 5.0.6 on 2024-07-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0002_authorbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
    ]
