# Generated by Django 5.0.6 on 2024-07-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0003_remove_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
