# Generated by Django 5.0.6 on 2024-06-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creator',
            new_name='user',
        ),
    ]
