# Generated by Django 5.0.6 on 2024-06-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0002_rename_creator_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='number_of_events',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='bands',
        ),
        migrations.CreateModel(
            name='BandEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.band')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='bands',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
