# Generated by Django 5.0.6 on 2024-06-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0003_alter_band_number_of_events_remove_event_bands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='isOpenAirEvent',
            field=models.BooleanField(),
        ),
    ]
