# Generated by Django 5.0.6 on 2024-06-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0004_alter_event_isopenairevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='isOpenAirEvent',
            field=models.BooleanField(default=False, verbose_name='Open Air Event'),
        ),
    ]
