# Generated by Django 5.0.6 on 2024-07-01 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('creationDate', models.DateField()),
                ('isRealEstate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('fixed-price', 'Fixed price'), ('variable-price', 'Variable price')], default='fixed-price', max_length=30)),
                ('isNewListing', models.BooleanField(default=False, verbose_name='Is new Listing')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ListingsApp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
